@host=https://localhost:7280
GET {{host}}/lms/courses/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDdkY2ExOC04NGQ3LTQxODEtYjQ5ZC01NWFmMzgzN2JjNTciLCJuYW1lIjoiYXNocmFmYWRtaW4iLCJqdGkiOiIwNjM0MGVjMi1hM2YwLTRlOWMtYmY5ZC05Nzc1YzNiNjFjMTgiLCJleHAiOjE2NjU4ODk1NjEsImlzcyI6ImxtcyIsImF1ZCI6ImxtcyJ9.1r1y4NN9VuNp4qgx3jR43Bk-WFQuurjfLPg0Aj7dYkM
